#!/bin/bash

### BEGIN INIT INFO
# Provides:nodejaiboxnano
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script for Nano  Application
# Description:       Script for Nano  Application
### END INIT INFO

# An application name to display in echo text.
# An application name to display in echo text.
# NAME="iBoxNanoFirmware"
# The full path to the directory containing the node and forever binaries.
# NODE_BIN_DIR=/home/node/local/node/bin
# Set the NODE_PATH to the Node.js main node_modules directory.
# NODE_PATH=/home/node/local/node/lib/node_modules
# The directory containing the application start Javascript file.
# APPLICATION_DIRECTORY=/home/node/my-application
# The application start Javascript filename.
# APPLICATION_START=start-my-application.js
# Process ID file path.
# PIDFILE=/var/run/my-application.pid
# Log file path.
# LOGFILE=/var/log/my-application.log

NAME="NanoNodeJS"
NODE_BIN_DIR=/usr/bin
NODE_PATH=/usr/local/lib/node_modules/
APPLICATION_DIRECTORY=/home/pi/ibox/
APPLICATION_START=iBoxWebGUI.js
PIDFILE=/var/run/$NAME.pid
LOGFILE_ERR=/home/pi/ibox/logs/iBoxWebGUI_Forever_Err.log
LOGFILE_LOG=/home/pi/ibox/logs/iBoxWebGUI_Forever_Log.log
LOGFILE_STDOUT=/home/pi/ibox/logs/iBoxWebGUI_Forever_StdOut.log
PATHPID=/var/run/
PATH=$NODE_BIN_DIR:$PATH

USER=root
HOME=/root

export USER HOME
export NODE_PATH=$NODE_PATH

start() {
        echo "Starting $NAME"
        /usr/local/bin/forever --pidFile $PIDFILE --sourceDir $APPLICATION_DIRECTORY \
                -p $PATHPID -a -l $LOGFILE_LOG -e $LOGFILE_ERR -o $LOGFILE_STDOUT --minUptime 5000 --spinSleepTime 2000 \
                start $APPLICATION_START &
        RETVAL=$?
}

stop() {
        if [ -f $PIDFILE ]; then
                echo "Shutting down $NAME"
                forever stop $APPLICATION_START
                RETVAL=$?
        else
                echo "$NAME is not running."
                RETVAL=0
        fi
}

restart() {
        echo "Restarting $NAME"
        stop
        start
}

status() {
        echo "Status for $NAME:"
        /usr/local/bin/forever list
        RETVAL=$?
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        status)
                status
                ;;
        restart)
                restart
                ;;
        *)
                echo "Usage: {start|stop|status|restart}"
                exit 1
                ;;
esac
exit $RETVAL
